import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Form from '../components/Form';
import FormContainer from '../components/FormContainer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Audio Quality Survey</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <FormContainer />
    </main>
  </div>
);

export default Home;
